### ISSUE TITLE
Can't build emscripten example

### ISSUE THREAD

**Issue by WebSeed** [brackeen/glfm#10]
Hi, I'm sure it's trivial (I'm new to C/C++) but when I follow the [instructions on the README](https://github.com/brackeen/glfm#emscripten) I get `fatal error: 'glfm.h' file not found`:

<img width="690" alt="screen shot 2018-03-05 at 07 25 55" src="https://user-images.githubusercontent.com/357579/36962209-868805a0-2046-11e8-95ef-42617148aa43.png">

If I manually copy the`glfm.h` into the source directory the example builds but I get `WARNING:root:emcc: cannot find library "glfm"` and the emscripten example loads in browser but just shows black square for content.

**Comment by brackeen** [comment]
I'm guessing this error happens when using the CMakeLists.txt in the `example` directory directly. Instead use the CMakeLists.txt from the root directory with the `-DGLFM_BUILD_EXAMPLE=ON` flag. (The root CMakeLists.txt includes the `example` CMakeLists.txt, not the other way around)

**Comment by WebSeed** [comment]
Ah yes, I thought I had to run this from the example directory for some reason. Running from root fixed everything, thanks.
