### ISSUE TITLE
Will OpenGL ES 3.0 work on WebGL?

### ISSUE THREAD

**Issue by NukeBird** [brackeen/glfm#13]
> and WebGL 1.0 (via Emscripten).

> OpenGL ES 2.0, 3.0, 3.1, and 3.2 display setup.

```cpp
  #elif defined(GLFM_PLATFORM_EMSCRIPTEN)
    #include <GLES3/gl3.h>
    #include <GLES3/gl2ext.h>
  #else
```

Does it mean that ES 3.0 can be used in WebGL 1.0? 
WebGL 1.0 based on ES 2.0, so it confused me a bit

**Comment by NukeBird** [comment]
So, WebGL 2.0 natively supported too?

If that so, why only version 1.0 mentioned in README.md?

**Comment by brackeen** [comment]
Personally I haven't tested WebGL 2.0, and support of it is largely dependent on Emscripten.

**Comment by NukeBird** [comment]
Ok, thank you
