### ISSUE TITLE
Building for ios simulator

### ISSUE THREAD

**Issue by glennerichall** [brackeen/glfm#19]
When building for ios simulator using cmake and ios-cmake-toolchain found at https://github.com/leetal/ios-cmake, this line triggers
https://github.com/brackeen/glfm/blob/d04ac865d02d8d253789da82bd21a0f62936c944/CMakeLists.txt#L18
clang: warning: no such sysroot directory: 'iphoneos' [-Wmissing-sysroot]
glfm-src/include/glfm.h:39:12: fatal error: 'TargetConditionals.h' file not found

but when commented, everything goes fine.
Not sure, but is it necessary that iphoneos is specified explicitely as cmake computes it?

**Comment by brackeen** [comment]
It looks like there is some sort of conflict between GLFM's CMake scripts and the one you are using. I added a conditional the GLFM's script, let me know if that works for you, or if you have another solution.

Here: 
https://github.com/brackeen/glfm/commit/f45b8c1e19d0ba7e16d8a635e0f8544cfa015a0f

**Comment by glennerichall** [comment]
Builds perfectly thanks
