### ISSUE TITLE
How to use GLFM in a real android project?

### ISSUE THREAD

**Issue by realaltffour** [brackeen/glfm#20]
I have a couple of questions on building and using GLFM on android thought of making it into one issue since I couldn't find one single tutorial on how to use this.

- What is happening in the CMakeLists.txt file in examples folder? Why there isn't the add_executable() function. ?

- Can I include GLFM with add_subdirectory(path/to/glfm) and link it with my project with target_link_libraries(project glfm)?

- What about in source build support?

- How would I compile it with Gradle?

I am sorry if I missed something in the README file.
Anyway, Thanks in advance!

**Comment by jadshep** [comment]
- `add_executable` is called in the `GLFMAppTarget.cmake` file that's included [here](https://github.com/brackeen/glfm/blob/f45b8c1e19d0ba7e16d8a635e0f8544cfa015a0f/example/CMakeLists.txt#L15) and uses the parameters set previously in that file.
- Yes
- Should work the same as with any CMake project
- CMake doesn't have an Android generator, so you have to create a project yourself in Android Studio. Then follow the directions [here](https://github.com/brackeen/glfm#android-studio-30).

**Comment by realaltffour** [comment]
Ok, Thanks!
