### ISSUE TITLE
Keyboard Input

### ISSUE THREAD

**Issue by nxtexe** [brackeen/glfm#29]
I was having an issue with getting keyboard input on mobile using emscripten. I have a canvas that covers the entire viewport. While I'm rendering to the canvas using OpenGL ES the canvas no longer responds to JS event listeners, so I had no way of getting the user keyboard up using HTML5 APIs since it requires a user gesture for activation. Does this library fix this issue? When running my code using this library in the browser, can I activate the soft keyboard programmatically?

**Comment by brackeen** [comment]
No, GLFM doesn't provide a way to show the soft keyboard programmatically on Emcripten (`glfmSetKeyboardVisible` works on native iOS and Android).

**Comment by nxtexe** [comment]
> No, GLFM doesn't provide a way to show the soft keyboard programmatically on Emcripten (`glfmSetKeyboardVisible` works on native iOS and Android).

Ok thanks for clearing that up. I'll close this thread
