### ISSUE TITLE
how about MacOS

### ISSUE THREAD

**Issue by jaccen** [brackeen/glfm#36]
i learn that can support ios android and web，  how about maos and windows?
how about vulkan?

**Comment by lance-loong** [comment]
This library is mobile. You can try glfw.

**Comment by lance-loong** [comment]
至于vulkan的,目前比较好的做法是,开启自己的分支/

**Comment by jaccen** [comment]
其实更想跨平台，不仅仅是mobile，而glfw对移动平台支持不好，因为跨平台经常在Pc下调试，比频繁走手机更方便~

**Comment by lance-loong** [comment]
目前没有好的办法,不过有个折中的办法.你可以将glfw按照glfm的接口封装起来,并且工作量很低.

**Comment by brackeen** [comment]
As stated, GLFM will probably never have Windows+macOS+Linux support, and GLFW is best suited for that.

An issue for vulkan is here: https://github.com/brackeen/glfm/issues/17

Additionally, I added an issue for macOS support via Catalyst, which would require minimum code changes (although OpenGL is not supported) https://github.com/brackeen/glfm/issues/37

Closing this issue in favor of the other two
