### ISSUE TITLE
Support something like UIImpactFeedbackGenerator (Device Vibrations)

### ISSUE THREAD

**Issue by orange451** [brackeen/glfm#42]
Hello! I would like to request support for UIImpactFeedbackGenerator. This is useful because as a software-user it is often gratifying to have some physical feedback when pressing a button. or completing a task.

This can be done on ios using:
https://developer.apple.com/documentation/uikit/uiimpactfeedbackgenerator

Would this be possible to integrate with GLFM API?

After seeing the "out of scope" section of the readme, I am unsure if this falls in to that category or not. I believe this should be supported though, as all of those categories (images/text/audio/ui/maps/etc) are generally supported by an entire library themselves. Whereas this would be a relatively small/simple addition to GLFM

**Comment by brackeen** [comment]
Yes, this makes sense to add, especially because (like you said) haptic feedback is often associated with touch.

I already have code for this in another project, I'll see if I can integrate it into GLFM in the next few days.

**Comment by orange451** [comment]
That would be awesome! I'll be looking forward to seeing that commit!! 😄

**Comment by brackeen** [comment]
This is now implemented, @orange451. Leaving the issue open for a while as I'll probably adjust the Android implementation.

**Comment by brackeen** [comment]
Closing this one. For reference:
```
glfmPerformHapticFeedback(display, GLFMHapticFeedbackMedium);
```
