### ISSUE TITLE
Context/Edit Menu Support

### ISSUE THREAD

**Issue by orange451** [brackeen/glfm#43]
Hey, I was curious if GLFM plans to support features like context menus or edit menus. Obviously these can be hand-made by the developer using custom UI, but wont have the native look or feel especially across devices.

Context menu:
https://developer.apple.com/documentation/uikit/uicontrol/adding_context_menus_in_your_app

Edit Menu:
https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/AddingCustomEditMenuItems/AddingCustomEditMenuItems.html

![image](https://user-images.githubusercontent.com/5247778/128530520-43fd4bdd-6022-407f-8e16-2da5fc678111.png)
![image](https://user-images.githubusercontent.com/5247778/128530012-b96950b7-ba6e-49b9-b9d5-0baa36bca9ea.png)

These kinds of menus would be great for creating tools/applications using GLFM instead for just creating games!

**Comment by orange451** [comment]
The only reason I ask is because I am actually using Java to develop my ios application using GLFM, so I do not have the ability to make these system-level api calls in a nice way.

**Comment by brackeen** [comment]
Yeah, this is out of scope for GLFM. It would be better to use a cross platform UI (like ImGui), or, if you need iOS-specific UI, you can use `glfmGetUIViewController` to access the UIViewController.
