### ISSUE TITLE
GLFMDepthFormat24 is a confusing name for Metal

### ISSUE THREAD

**Issue by chaoticbob** [brackeen/glfm#48]
The enum name [GLFMDepthFormat24 is a little confusing since GLFMDepthFormat24 resolves to MTLPixelFormatDepth32Float](https://github.com/brackeen/glfm/blob/main/src/glfm_apple.m#L207).

It lead me to believe that 32-bit depth wasn't supported. 

Is it possible to have a less confusing name?

**Comment by brackeen** [comment]
Thanks for the suggestion. A `GLFMDepthFormat32` enum was added for clarity.
