### ISSUE TITLE
Targeting API 21 on emulator crashes in glfm__getSystemWindowInsets().

### ISSUE THREAD

**Issue by stirlingboy69** [brackeen/glfm#50]
Hello brackeen,

While playing around with your glfm framework I came across a crash in the glfm__getSystemWindowInsets() function. 
On a windows emulator, when I targeted API 21 the java call to getRootWindowInsets would crash with a segfault. After a little
Googling I found that getRootWindowInsets() was introduce in API 23, but the if check (line 1980) exits the function if the API is
less than 20. I think this maybe a typo, because in the other function glfm__getSafeInsets() checks if the API is at least 28 before you make the Java call to getRootWindowInsets().
Anyway, this a great framework you have written.

**Comment by brackeen** [comment]
Thanks for the report, this is now fixed. There was also an issue with incorrect insets when rotating on API 16, this was fixed as well.
