### ISSUE TITLE
Linux platform support

### ISSUE THREAD

**Issue by Tarik02** [brackeen/glfm#7]
Why only "mobile"? Maybe add also Linux support?

**Comment by brackeen** [comment]
What you're looking for is [GLFW](https://github.com/glfw/glfw). It supports Windows, Mac, Linux. GLFM is inspired by it.

**Comment by Tarik02** [comment]
@brackeen I want Windows, Mac, Linux, Android, iOS support in one.

**Comment by KyleCharters** [comment]
I believe what your asking for is out of the scope of the project. Glfw already supports desktops, and it does so very well. If you need support for all platforms under a single interface, just write an abstraction layer.
