### ISSUE TITLE
Add a desktop platform

### ISSUE THREAD

**Issue by iboB** [brackeen/glfm#9]
Why don't you create a desktop platform (say, based on SDL or GLFW) to make it easier for development?

If you're interested in this, I may try adding it too. Just say if you care whether SDL or GLFW (or something else) should be used as the underlying platform independent layer.

**Comment by brackeen** [comment]
A desktop platform is really out of scope for this project, and I'm not show how it would make development easier.

If you're making an app that works on both desktop and mobile, using both GLFW and GLFM is a pretty good idea, since they are pretty similar.

**Comment by iboB** [comment]
Of course if you want to release to a desktop platform glfm doesn't have enough features for all configurations (like for example GLFW does). My point is that during development is often much easier and faster to debug a native application, than deal with simulators and emulators (or, even worse, browsers). The ability to use your favorite debugger is a big advantage and time-saver in development. 

A glfm desktop platform wouldn't be meant for releasing to a desktop target but for fast development, where the programmers can spend most of their time using their favorite IDEs and debuggers. 

A big additional feature is hot-swapping code, which is often impractical to impossible on glfm's current target platforms, but relatively easy on desktop ones. Hot-swapping is typically reserved for the development cycle and disabled in releases, which have binaries linked into a single executable for optimization.

**Comment by Mark-Weston** [comment]
Wouldn't a GLFW backend do fine?

**Comment by brackeen** [comment]
This idea is really out of scope for this project, and could potentially cause more problems than it solves. (GLES contexts may not be available on all systems, for example)

If you don't want to use Xcode, Android Studio, or the simulators for everyday development, I'd recommend using GFLW instead, and later port the app to GLFM.
